# Generated by Django 4.2 on 2023-06-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_pokemon_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
